- name: variables to print
  hosts: web
  vars: # this play level, will have access to all play
   Course: "Devops with AWS"
   Trainer: "Sivakumar"
  tasks: 
   - name: print the information
     ansible.builtin.debug:
       msg: "Iam learning {{Course}} and trainer is {{Trainer}}"

   - name: print the information again
     vars: #override
      Course: "Ansible"
     ansible.builtin.debug:
       msg: "Iam learning {{Course}} and trainer is {{Trainer}}"

   - name: playbook-03
     ansible.builtin.debug:
       msg: "Iam learning {{Course}} and trainer is {{Trainer}}"
    