- name: print the information
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
   - name: print the course info
     ansible.builtin.debug:
      msg: "Iam learing {{Course}} and trainer is {{Trainer}}"