- name: Variables to print
  hosts: web
  vars_prompt:
  - name: Course
    prompt: Please enter the course name
  - name: Trainer
    prompt: Please enter trainer name  
  tasks:
  - name: print the course info
    ansible.builtin.debug:
     msg: "Iam learning {{Course}} and trainer is {{Trainer}}"    