- name: check given number is less than or greater than
  hosts: local
  connection: local
  vars:
    my_number: 20
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given number {{my_number}}, is less than 10"
    when: my_number < 10

  - name: print this greater than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{my_number}}, is greater than or equal to 10"
    when: my_number >= 10        