- name: Create user
  hosts: web
  become: yes
  tasks:
  - name: check usre exists or not
    ansible.builtin.command: id expense
    register: USER # here user is a variable that gets output from above command

  - name: print the user info
    ansible.builtin.debug:
      msg: "User info: {{USER}}"